apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-eta-deploy
  labels:
    app: healthcare-eta-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare-eta-app
  template:
    metadata:
      labels:
        app: healthcare-eta-app
    spec:
      containers:
      - name: healthcare-eta-container
        image: mrnumbrithdocker/healthcare:latest
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-eta-np-service1
  labels:
    app: healthcare-eta-app1
spec:
  selector:
    app: healthcare-eta-app

  type: NodePort
  ports:
  - nodePort: 31111    
    port: 8082
    targetPort: 8082
